### ISSUE TITLE
Help wanted!

### ISSUE THREAD

**Issue by Damazinho** [klaasnicolaas/python-energyzero#11]
@klaasnicolaas: Any hints how I can install this in my Home Assistant Supervised?

**Comment by klaasnicolaas** [comment]
If you run supervised then you also know how to do that 😉 
This is only the python package, the final integration for Home Assistant is still being worked on

**Comment by thijstriemstra** [comment]
> Any hints how I can install this in my Home Assistant Supervised?

Here's how I did it on a Raspberry Pi 4 (with RPI OS Lite and Home Assistant Supervised):

```console
# create custom_components
sudo mkdir /usr/share/hassio/homeassistant/custom_components

# copy energyzero from https://github.com/home-assistant/core/tree/dev/homeassistant
cp -R energyzero /usr/share/hassio/homeassistant/custom_components/
```

Make sure to add a `version: "0.0.1"` in the `energyzero/manifest.json` file.

Restart Home Assistant and add the `energyzero` integration in the UI.

In the home assistant log file it shows it's loaded:

```
[homeassistant.loader] We found a custom integration energyzero which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

![table with pricing](https://user-images.githubusercontent.com/305679/215159454-69509736-ec24-4d9f-a094-c94d9180c20b.JPG)

Hopefully energyzero will be part of Home Assistant soon and this hack isn't needed anymore. I'm new to home assistant so if there's a better way to install the energyzero at the moment please let me know!

**Comment by klaasnicolaas** [comment]
The integration is in the February release and you can already try it out in the beta (or install it as a custom component).

> ps. I wouldn't mind helping with a dutch translation

The translation has already been done, no further help is needed 😉
