### ISSUE TITLE
why poetry and rust needed? 

### ISSUE THREAD

**Issue by RonGroen** [klaasnicolaas/python-energyzero#30]
Fantastic, an solution that "reads" the ANWB -energy prices in HA.
And an integration in HA is nice, but why do I need poetry and rust.
I try to keep my server (pi) up-to-date with the apt-get commands.
And sometimes I update HA, unfortunately it does not update automatically itself.

Adding poetry and rust adds risks of hacks if I don't manually update those packages.
And I don't want to wait time with those things.
Hopefully you can make an update that is more hack-proof.

**Comment by klaasnicolaas** [comment]
If you use the integration you don't have to install any extra packages at all, based on your information I don't quite understand what your method is and whether I can help you 🤷🏻‍♂️

**Comment by RonGroen** [comment]
thank you for your quick response.
The documentation says : 
1: Setting up development environment
This Python project is fully managed using the [Poetry](https://python-poetry.org/) dependency manager.
You need at least:
Python 3.9+
[Poetry](https://python-poetry.org/docs/#installation)
...
Ok. I will continue without:
I upgraded HA to Home Assistant 2023.1.7
Installed: pip install energyzero (no errors)
restarted  HA
Settings, Devices and services, Integrations, Integrations
add integration, on select brand  search energyzero
Nothing: What could have gone wrong?
(no loglines, no notifications)

**Comment by klaasnicolaas** [comment]
I think you are mixing up a few things. The python package in this repository and the Home Assistant integration are two separate projects, but one ultimately uses the other to retrieve data.

The documentation described in this repository is for those who want to help develop the python package, so you don't need Poetry for use in Home Assistant. If you currently want to use the EnergyZero integration, you must install at least version [2023.2 (currently in beta)](https://rc.home-assistant.io/blog/2023/01/25/release-20232/) of Home Assistant, the integration will be available for everyone next Wednesday.

To come back on why `rust`, this is a package that is needed to run Home Assistant core on a Raspberry Pi, but has nothing to do with EnergyZero.
