### ISSUE TITLE
Feature request: Add Energy Tax to total price

### ISSUE THREAD

**Issue by imredamen** [klaasnicolaas/python-energyzero#35]
Great ro have this, especially as a component in home-assistant.

Would it be possible to also add the energy tax to the tariff displayed?
Now there is the incl. / excl. BTW option. In NL we also need to pay tax (+vat over the tax) on top of these rates:

for Gas 2023 - € 0,48980 ex BTW = €0,592658 incl BTW

for Electricity - € 0,12599 ex BTW = €0,1524479 incl BTW

so yes, about half the net price is in additional taxes..

Source for taxes: https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/overige_belastingen/belastingen_op_milieugrondslag/tarieven_milieubelastingen/tabellen_tarieven_milieubelastingen?projectid=6750bae7%2D383b%2D4c97%2Dbc7a%2D802790bd1110

**Comment by nicokars** [comment]
> Great ro have this, especially as a component in home-assistant.
> 
> Would it be possible to also add the energy tax to the tariff displayed? Now there is the incl. / excl. BTW option. In NL we also need to pay tax (+vat over the tax) on top of these rates:
> 
> for Gas 2023 - € 0,48980 ex BTW = €0,592658 incl BTW
> 
> for Electricity - € 0,12599 ex BTW = €0,1524479 incl BTW
> 
> so yes, about half the net price is in additional taxes..
> 
> Source for taxes: https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/overige_belastingen/belastingen_op_milieugrondslag/tarieven_milieubelastingen/tabellen_tarieven_milieubelastingen?projectid=6750bae7%2D383b%2D4c97%2Dbc7a%2D802790bd1110

https://student-techlife.com/2023/01/11/energyzero-market-prices-with-new-integration-in-home-assistant/?fbclid=IwAR1DCcvuUQaHfdz3axBNrkgk2fOyAsinzBXRb_UjwthEGoj4claYt7Qq9us

**Comment by klaasnicolaas** [comment]
This is not the right place for feature requests for the home assistant integration, please check the [community forum](https://community.home-assistant.io/c/feature-requests/13) for this. This repository is the underlying package that the integration uses to retrieve the data.

But to answer your question, see my [response](https://community.home-assistant.io/t/hourly-electricity-prices-netherlands/485842/67) in a forum topic about the integration.

**Comment by imredamen** [comment]
Very helpful, thanks! Let me close this one.

**Comment by imredamen** [comment]
Not the right place, links to guidance were given
